name: tremor
description: Gradution project for FCIS MU Bio department

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_analytics: ^9.1.2
  share_plus: ^4.0.1
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  dio: ^4.0.4
  easy_localization: ^3.0.0
  connectivity_plus: ^2.2.1
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.9
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1


  #TODO: run these commands
  #flutter pub run flutter_native_splash:create
  #flutter pub run flutter_launcher_icons:main
  #pub global activate rename #to activate rename package
  #pub global run rename --bundleId com.hady.dev.#appname here#
  #pub global run rename --appname "#appname here#"
flutter_app_name:
  name: "Tremor"

flutter_native_splash:
  color: "" #TODO: add your app splash light theme color like "#FEF6F4"
  image:   #TODO: add your app image on splash light theme image like assets/images/app_icon_light.png in png format
  color_dark: "" #TODO: add your app splash dark theme color like "#323031"
  image_dark: #TODO: add your app image on splash dark theme image like assets/images/app_icon_dark.png in png format
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "" #TODO: add your app icon here in png format
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/
